version: "3"
services:
  gateway:
    restart: unless-stopped
    image: staticfloat/nginx-certbot:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    environment:
      - CERTBOT_EMAIL
  docs:
    image: ghcr.io/earthcubegeochron/sparrow/documentation-site:latest
volumes:
  letsencrypt:

