version: "3"
services:
  gateway:
    restart: unless-stopped
    image: staticfloat/nginx-certbot:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - htdocs:/www/data
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    environment:
      - CERTBOT_EMAIL
  webhook:
    restart: unless-stopped
    image: staticfloat/docker-webhook
    volumes:
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8000
    environment:
      - GITHUB_TOKEN
      - GITHUB_ACTOR
      - WEBHOOK_SECRET
      - WEBHOOK_HOOKS_DIR=/code/hooks
      - WEBHOOK_BRANCH_LIST=master,docs
  frontend:
    image: docker.pkg.github.com/earthcubegeochron/sparrow/sparrow-documentation-site:latest
    volumes:
      - htdocs:/public
    command: npm run build
volumes:
  letsencrypt:
  htdocs:

