version: "3"
services:
  gateway:
    # Temporarily (hopefully) maintain our own fork
    # should eventually revert to the below
    # image: staticfloat/nginx-certbot
    build: "https://github.com/UW-Macrostrat/docker-nginx-certbot.git#:src"
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./htdocs:/www/data
      - ./conf.d:/etc/nginx/user.conf.d:ro
    environment:
      - CERTBOT_EMAIL=daven.quinn@wisc.edu

