version: "3"
services:
  gateway:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80/tcp
      - 8443:443/tcp
    volumes:
      - ./htdocs:/www/data
    environment:
      - CERTBOT_EMAIL=daven.quinn@wisc.edu
