version: "3"
services:
  gateway:
    restart: unless-stopped
    image: staticfloat/nginx-certbot:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./htdocs:/www/data
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    environment:
      - CERTBOT_EMAIL=daven.quinn@wisc.edu
volumes:
  letsencrypt:

